### PR TITLE
[PROPOSAL] Use system libraries for dependencies

### PR DESCRIPTION
**Pull request by frabert**
As libdmusic is going to probably be managed as a vcpkg dependency, we will finally have a package manager available for both Windows and Linux systems. As such, I think using system-provided libraries is going to be the better option in the long run.

Main advantages:
- Faster clones (no more `--recursive`)
- Faster builds (dependencies are prebuilt, allows for caching of dependencies)
- Better integration with native package managers (if we want to provide prebuilt binaries, for instance)

By using modules for packages that do not natively provide CMake configuration files, we ensure that both vcpkg-installed and (for example) apt-installed packages can be found.
The libsquish package for vcpkg has been submitted (https://github.com/Microsoft/vcpkg/pull/6038), for the time being it is only available in the REGoth fork.

### CODE REVIEW

**Comment by ataulien** [comment]
Can't we just add a PPA containing those libraries to travis?

**Comment by frabert** [comment]
I wasn't able to find PPAs for those packages. They should all be "self-sufficient" in that they do not depend on other system libraries, so maybe we can just use the packages from more recent versions of Ubuntu. If all else fails, Travis should have a cache we can use to build them from source once and then reuse them

**Comment by frabert** [comment]
I've solved the issue by using vcpkg, which indeed allows us to use a universal repository, even for different linux distros that may or may not have the packages we need

**Comment by ataulien** [comment]
Can you update the Readme with the new build instructions and dependencies too?

**Comment by frabert** [comment]
I've added instructions for both vcpkg and the native package managers

**Comment by ataulien** [comment]
Seems like the `libphysfs-dev` package is not up to date in the ubuntu repositories (19.04 beta):

```
:137 (message):
  Could NOT find PhysFS: Found unsuitable version "2.1.1", but required is at
  least "3" (found /usr/local/lib/libphysfs.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPhysFS.cmake:64 (find_package_handle_standard_args)
  vdfs/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/andre/code/zenlib-vcpkg/ZenLib/build/CMakeFiles/CMakeOutput.log"
```

Although `apt` tells me I've got version `3.0.1-3.1build1` of the package?

**Comment by frabert** [comment]
Is it possible that you have installed PhysFS in the past from source? That is not where `apt` normally puts the packages, it should be found in `/usr/lib/x86_64-linux-gnu/libphysfs.so`

Try running `cmake -DCMAKE_IGNORE_PATH=/usr/local/lib;/usr/local/include ..`, maybe we can make cmake ignore the local package

**Comment by ataulien** [comment]
Spot on, that works! So since that is just my fault everything should be fine with the pr. 

Thanks a lot!

**Pull request merged**
