### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by Try**
HI!

I'm developer of an gothic2 remake, here some changes to make loading faster:
  1. optimize dds loader
  2. change signature for readEntry, to avoid multiple temporary string creation

### CODE REVIEW

**Comment by ataulien** [comment]
Thanks for the PR!

Some questions:
- Do you have a rough estimate on how much load-times improved? Just curious.
- What was the reason of the PhysFS submodule update hidden in the DDS related commit?

Also, what kind of remake are you working on? Sounds interesting :smiley:

**Comment by Try** [comment]
1. OK, I've made a very simple benchmark, and run it 3 times:
` const char* tst="MOWOTREETOP02-C.TEX"`
  `std::vector<uint8_t> data;`
  `std::vector<uint8_t> ztex;`
  `gothicAssets.getFileData(tst,data);`
  `auto t = Application::tickCount();`
  `Log::d("start test");`
  `for(int i=0;i<1000;++i){`
  `    ZenLoad::convertZTEX2DDS(data,ztex);`
  `    }`
  `Log::d("time = ",Application::tickCount()-t);`

Results on non optimized function:
* time = 2509
* time = 2370
* time = 2327
After optimization:
* time = 246
* time = 204
* time = 148
compiler is mingw32 (v 5.3)

2. About PhysFS - this is my mistake. It seem I have, for some reason, an other version of  this library in my fork. Probably I should fix it and create another PR

About remake: simple G2Notr remake :) I've been working on it for 2 months, so not a lot of stuff there, here is some screenshot: https://imgur.com/a/fQqznhG

**Comment by ataulien** [comment]
Those benchmarks look promising! Awesome!

> About remake: simple G2Notr remake :) I've been working on it for 2 months, so not a lot of stuff there, here is some screenshot: https://imgur.com/a/fQqznhG

Your "simple" remake is already looking impressive for only being in development for 2 months. Did you write the engine yourself? 

> 1. About PhysFS - this is my mistake. It seem I have, for some reason, an other version of  this library in my fork. Probably I should fix it and create another PR

You may also kill/modify the commit using a rebase and force-push.

**Comment by markusobi** [comment]
I recently learnt about `git push --force-with-lease`. Force, but with seatbelt on: it won't drop commits of other people.

**Comment by Try** [comment]
> You may also kill/modify the commit using a rebase and force-push.
Done, I hope it's alright now. 

>Did you write the engine yourself?
Cant call this engine: there are bullet physic + vulkan renderer + no sound :)

**Comment by ataulien** [comment]
Sorry this took me so long to merge. I wasn't aware you fixed the PhysFS thing. Thanks for the improvements!

**Pull request merged**
