### PR TITLE
Daedalus compiler

### PR DESCRIPTION
**Pull request by Hedede**
I'm creating a pull request so that additions can be reviewed and progress can be tracked.

It is not ready to be merged, as I haven't finished importing my code yer, and there's a cleanup to do.

### CODE REVIEW

**Comment by ataulien** [comment]
Cool! I will gladly wait until you have ported all your code over!

**Comment by ataulien** [comment]
How is progress going on this? Is it ready to be merged yet?

**Comment by Hedede** [comment]
I haven't been able to work on this for past few weeks. There is still some code left to port over (mostly test code), and I want to finish .src processer before merge.

**Comment by Jurigag** [comment]
With this added there will be possibility to make some standalone daedalus compiler for original gothic? @Hedede  I would like to see just some fast, lightweight compiler which could be used with appveyor to for example test script compilation if no errors.

**Comment by Hedede** [comment]
@Jurigag Yes, that was my intention when I started the project.

**Comment by ataulien** [comment]
I'm closing this as the last update to this PR is from 2017.

**Pull request closed without merging**
